{{- if and .Values.rbac.create .Values.rbac.leaderElection.createRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "configpropagation.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "configpropagation.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "configpropagation.fullname" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "configpropagation.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
