apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configpropagations.configpropagator.platform.example.com
spec:
  group: configpropagator.platform.example.com
  scope: Namespaced
  names:
    kind: ConfigPropagation
    listKind: ConfigPropagationList
    plural: configpropagations
    singular: configpropagation
    shortNames:
      - cprop
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Targets
          type: integer
          jsonPath: .status.targetCount
        - name: Synced
          type: integer
          jsonPath: .status.syncedCount
        - name: OutOfSync
          type: integer
          jsonPath: .status.outOfSyncCount
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          description: ConfigPropagation declares propagation of a source ConfigMap to target namespaces.
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required: [sourceRef, namespaceSelector]
              properties:
                sourceRef:
                  type: object
                  required: [namespace, name]
                  properties:
                    namespace:
                      type: string
                      minLength: 1
                    name:
                      type: string
                      minLength: 1
                namespaceSelector:
                  type: object
                  description: Label selector to choose target namespaces
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                    matchExpressions:
                      type: array
                      items:
                        type: object
                        required: [key, operator]
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                            enum: [In, NotIn, Exists, DoesNotExist]
                          values:
                            type: array
                            items:
                              type: string
                dataKeys:
                  type: array
                  items:
                    type: string
                strategy:
                  type: object
                  properties:
                    type:
                      type: string
                      enum: [rolling, immediate]
                      default: rolling
                    batchSize:
                      type: integer
                      minimum: 1
                      default: 5
                conflictPolicy:
                  type: string
                  enum: [overwrite, skip]
                  default: overwrite
                prune:
                  type: boolean
                  default: true
                resyncPeriodSeconds:
                  type: integer
                  minimum: 10
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    required: [type, status]
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum: [True, False, Unknown]
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                targetCount:
                  type: integer
                  minimum: 0
                syncedCount:
                  type: integer
                  minimum: 0
                outOfSyncCount:
                  type: integer
                  minimum: 0
                outOfSync:
                  type: array
                  items:
                    type: object
                    required: [namespace, reason]
                    properties:
                      namespace:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                lastSyncTime:
                  type: string
                  format: date-time
