replicaCount: 1

image:
  repository: ghcr.io/example/configpropagation-operator
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

rbac:
  create: true
  leaderElection:
    createRole: true

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

resources: {}

affinity: {}

nodeSelector: {}

tolerations: []

topologySpreadConstraints: []

env:
  batchSize: 5
  workers: 4
  resyncSeconds: 30
  extra: []

args: []

leaderElection:
  enabled: false

healthProbe:
  bindAddress: ":8081"

livenessProbe:
  enabled: true
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  enabled: true
  httpGet:
    path: /readyz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 3

metrics:
  enabled: true
  bindAddress: ":8080"
  port: 8080

webhook:
  enabled: true
  port: 9443
